### ISSUE TITLE
Add meta info to package.json

### ISSUE THREAD

**Issue by Strajk** [mncharlton/cypress-random-test-order#1]
Hi 👋 

Seeing your comment here https://github.com/cypress-io/cypress/issues/2908#issuecomment-659507150 I was curious how you made it work, so I went to npm but there was no link to the repo.

So I had to put an "effort" 😅 to find the repo on GitHub :D

It's easy to add these links by adding `repository` and `homepage` fields to package.json:

![image](https://user-images.githubusercontent.com/697301/87797192-a6cfe900-c84a-11ea-8e5c-fbdcf4b0f09c.png)

**Comment by mncharlton** [comment]
Whoops! Leaving that out was an oversight, I've just added it and republished, thanks!
